name: nlp-pipeline-py311
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - numpy==1.26.4
      - pandas==2.2.2
      - scipy==1.12.0
      - scikit-learn==1.4.2
      - joblib==1.4.2
      - matplotlib==3.8.4
      - torch==2.2.2
      - transformers==4.40.2
      - datasets==2.19.0
      - accelerate==0.30.1
      - tqdm==4.66.4
      - lightgbm==4.3.0
      - azure-ai-ml==1.15.0
      - azure-identity==1.17.1
